# -*- coding: utf-8 -*-
"""Base de verbos irregulares de los mini tests de 6to.

Cada entrada: (infinitivo, past simple, past participle, why, tip)
Las formas son las que se MUESTRAN y las que se aceptan. Las variantes
extra (was/were, gotten, lighted) se agregan en EXTRA.
"""

VERBS = {
"be":        ("be","was / were","been",
              "be is the strangest verb of all: it has two past simple forms, was for I, he, she and it, and were for you, we and they, but only one past participle, been.",
              "After have or has there is only one possible word: been. have was does not exist."),
"beat":      ("beat","beat","beaten",
              "beat does not change in the past simple, but the past participle adds -en: beaten.",
              "The first two forms look the same, so the only new letters you write are -en."),
"become":    ("become","became","become",
              "become follows come: the past simple changes the o into an a, and the past participle goes back to the infinitive.",
              "The first and the third form are the same word. Only the middle one changes."),
"begin":     ("begin","began","begun",
              "begin changes its vowel twice: i in the infinitive, a in the past simple and u in the past participle.",
              "i - a - u, the same road as drink - drank - drunk and sing - sang - sung."),
"bite":      ("bite","bit","bitten",
              "bite drops the e for the past simple, bit, and doubles the t for the participle: bitten.",
              "Two t in bitten. With one t it is the past simple."),
"blow":      ("blow","blew","blown",
              "blow belongs to the -ew / -own family: blew for the past simple and blown for the participle.",
              "blew sounds like the colour blue, but after have you need blown."),
"break":     ("break","broke","broken",
              "break changes ea into o for the past simple and the participle adds -n: broken.",
              "broke is the past simple. The one that follows have or has is broken."),
"bring":     ("bring","brought","brought",
              "bring takes -ought for both past forms, so the second and the third are the same word: brought.",
              "brought, bought and thought all end the same way and all rhyme."),
"build":     ("build","built","built",
              "build turns its d into a t: built, for the past simple and for the participle.",
              "There is no -ed anywhere in this verb."),
"buy":       ("buy","bought","bought",
              "buy also goes to -ought, and the second and the third form are the same: bought.",
              "bought is already past, so you never add -ed on top of it."),
"catch":     ("catch","caught","caught",
              "catch loses the -tch and takes -aught for both past forms: caught.",
              "caught starts c-a-u, never c-o-u."),
"choose":    ("choose","chose","chosen",
              "choose drops one o for the past simple, chose, and the participle adds -n: chosen.",
              "choose has two o; chose and chosen have only one."),
"come":      ("come","came","come",
              "come changes o into a for the past simple, and the participle goes back to come.",
              "The first and the third form are the same word, like become."),
"cost":      ("cost","cost","cost",
              "cost never changes: the three forms are exactly the same word.",
              "If you add -ed to cost, it is wrong."),
"cut":       ("cut","cut","cut",
              "cut never changes, like put, hit and shut.",
              "Short verbs that already end in -t often keep the same shape three times."),
"do":        ("do","did","done",
              "do has three different forms: do, did and done.",
              "did is the past simple. After have or has you need done."),
"draw":      ("draw","drew","drawn",
              "draw belongs to the -ew / -own family: drew for the past simple and drawn for the participle.",
              "drawn ends in -n, like known, grown and thrown."),
"drink":     ("drink","drank","drunk",
              "drink changes i into a and then into u: drink, drank, drunk.",
              "i - a - u, the same road as begin, sing and ring."),
"drive":     ("drive","drove","driven",
              "drive changes i into o for the past simple and adds -n for the participle: driven.",
              "driven has one v and ends in -en, like given and ridden."),
"eat":       ("eat","ate","eaten",
              "eat has three different forms: eat, ate and eaten.",
              "ate is the past simple. have ate is always wrong."),
"fall":      ("fall","fell","fallen",
              "fall changes a into e for the past simple and the participle adds -en: fallen.",
              "fell is the past simple. After have it is fallen."),
"feel":      ("feel","felt","felt",
              "feel loses one e and ends in -t: felt, for the past simple and for the participle.",
              "felt, kept and slept all belong to the same family."),
"fight":     ("fight","fought","fought",
              "fight goes to -ought for both past forms: fought.",
              "fought, bought, brought and thought all rhyme."),
"find":      ("find","found","found",
              "find changes i into ou: found, for the past simple and for the participle.",
              "There is no -ed in this verb, and the two past forms are the same."),
"fly":       ("fly","flew","flown",
              "fly belongs to the -ew / -own family: flew for the past simple and flown for the participle.",
              "flied does not exist."),
"forget":    ("forget","forgot","forgotten",
              "forget follows get, and the past participle doubles the t: forgotten.",
              "Two t in forgotten. With one t it is the past simple."),
"get":       ("get","got","got",
              "get changes e into o: got, for the past simple and for the participle.",
              "In British English the participle is got, exactly like the past simple."),
"give":      ("give","gave","given",
              "give changes i into a for the past simple and adds -n for the participle: given.",
              "gave is the past simple; given is the one that follows have or has."),
"go":        ("go","went","gone",
              "go is special: the past simple, went, does not look like go at all, and the participle is gone.",
              "went can never follow have. You say I have gone."),
"grow":      ("grow","grew","grown",
              "grow belongs to the -ew / -own family: grew for the past simple and grown for the participle.",
              "growed is not a word."),
"hang":      ("hang","hung","hung",
              "hang changes a into u: hung, for the past simple and for the participle.",
              "hung is the word for a coat or a picture."),
"have":      ("have","had","had",
              "have becomes had for both past forms.",
              "In the present perfect you can see the two of them together: I have had."),
"hear":      ("hear","heard","heard",
              "hear only adds a d, and the sound changes: heard, twice.",
              "It is written with the same letters as hear, plus a d."),
"hide":      ("hide","hid","hidden",
              "hide drops the e for hid and doubles the d for hidden.",
              "Two d in hidden."),
"hit":       ("hit","hit","hit",
              "hit never changes: the three forms are the same word.",
              "hitted does not exist."),
"hold":      ("hold","held","held",
              "hold changes o into e: held, for the past simple and for the participle.",
              "held is short and has no -ed."),
"hurt":      ("hurt","hurt","hurt",
              "hurt never changes, like hit, cut and put.",
              "If you add anything to hurt, it is wrong."),
"keep":      ("keep","kept","kept",
              "keep loses one e and ends in -t: kept, twice.",
              "keep, sleep and feel all end in -t in the past."),
"know":      ("know","knew","known",
              "know belongs to the -ew / -own family: knew for the past simple and known for the participle.",
              "The k at the beginning is silent, but you still have to write it."),
"lay":       ("lay","laid","laid",
              "lay means to put something down on a surface, and both its past forms are laid.",
              "Do not mix it with lie - lay - lain, which is a different verb."),
"leave":     ("leave","left","left",
              "leave becomes left for both past forms.",
              "left is also a direction, but here it is the past of leave."),
"lend":      ("lend","lent","lent",
              "lend turns its d into a t: lent, twice.",
              "lend, send and spend all work exactly the same way."),
"let":       ("let","let","let",
              "let never changes.",
              "letted does not exist."),
"lie":       ("lie","lay","lain",
              "lie means to rest on a bed or on the floor, and its forms are lie, lay and lain.",
              "The past simple of lie is lay, and that is why these two verbs are so easy to mix."),
"light":     ("light","lit","lit",
              "light becomes lit for both past forms.",
              "lighted also exists in English, but the list of this class uses lit."),
"lose":      ("lose","lost","lost",
              "lose adds a t and drops the e: lost, twice.",
              "lose has one o. loose, with two, is a different word."),
"make":      ("make","made","made",
              "make turns the k into a d: made, for the past simple and for the participle.",
              "made already carries its d, so maked does not exist."),
"mean":      ("mean","meant","meant",
              "mean adds a t: meant, twice.",
              "It is written meant, but it sounds like ment."),
"meet":      ("meet","met","met",
              "meet loses one e: met, twice.",
              "Two e in meet, one in met."),
"pay":       ("pay","paid","paid",
              "pay changes the y into an i and adds a d: paid, twice.",
              "payed with a y does not exist."),
"put":       ("put","put","put",
              "put never changes.",
              "putted does not exist."),
"read":      ("read","read","read",
              "read is written exactly the same three times, but the two past forms sound like red.",
              "Your eyes see the same word; your mouth says a different one."),
"ride":      ("ride","rode","ridden",
              "ride changes i into o for the past simple and the participle doubles the d: ridden.",
              "Two d in ridden. rode is the past simple."),
"ring":      ("ring","rang","rung",
              "ring follows i - a - u: ring, rang, rung.",
              "The same road as sing, drink and begin."),
"rise":      ("rise","rose","risen",
              "rise changes i into o for the past simple and adds -n for the participle: risen.",
              "rose is also a flower, but here it is the past of rise."),
"run":       ("run","ran","run",
              "run changes u into a for the past simple and goes back to run for the participle.",
              "The first and the third form are the same word, like come."),
"say":       ("say","said","said",
              "say becomes said for both past forms.",
              "It is written said, but it sounds like sed."),
"see":       ("see","saw","seen",
              "see has three different forms: see, saw and seen.",
              "saw is the past simple. After have or has it is seen."),
"sell":      ("sell","sold","sold",
              "sell changes -ell into -old: sold, twice.",
              "sell and tell work the same way: sold and told."),
"send":      ("send","sent","sent",
              "send turns its d into a t: sent, twice.",
              "send, lend and spend are the same family."),
"shine":     ("shine","shone","shone",
              "shine changes i into o: shone, twice.",
              "In British English shone rhymes with gone."),
"shoot":     ("shoot","shot","shot",
              "shoot loses one o: shot, twice.",
              "Two o in shoot, one in shot."),
"show":      ("show","showed","shown",
              "show is half regular: the past simple is showed, with -ed, but the past participle is shown.",
              "This is the trap: showed for the past simple, shown after have or has."),
"shut":      ("shut","shut","shut",
              "shut never changes.",
              "shutted does not exist."),
"sing":      ("sing","sang","sung",
              "sing follows i - a - u: sing, sang, sung.",
              "sang is the past simple; sung is the one that follows have."),
"sit":       ("sit","sat","sat",
              "sit changes i into a: sat, twice.",
              "One t in sat."),
"sleep":     ("sleep","slept","slept",
              "sleep loses one e and ends in -t: slept, twice.",
              "sleep, keep and feel all go the same way."),
"speak":     ("speak","spoke","spoken",
              "speak changes ea into o for the past simple and the participle adds -n: spoken.",
              "spoke is the past simple; spoken follows have or has."),
"spend":     ("spend","spent","spent",
              "spend turns its d into a t: spent, twice.",
              "spend, send and lend are the same family."),
"stand":     ("stand","stood","stood",
              "stand changes a into oo: stood, twice.",
              "Two o in stood."),
"steal":     ("steal","stole","stolen",
              "steal changes ea into o for the past simple and the participle adds -n: stolen.",
              "stolen ends in -en, like spoken and broken."),
"swim":      ("swim","swam","swum",
              "swim follows i - a - u: swim, swam, swum.",
              "swum, with a u, is the one that follows have."),
"take":      ("take","took","taken",
              "take changes a into oo for the past simple and the participle adds -n: taken.",
              "took is the past simple; taken follows have or has."),
"teach":     ("teach","taught","taught",
              "teach loses the -ch and takes -aught: taught, twice.",
              "catch and teach are a pair: caught and taught."),
"tear":      ("tear","tore","torn",
              "tear changes ea into o: tore for the past simple and torn for the participle.",
              "Here tear means to break paper, and it sounds like air."),
"tell":      ("tell","told","told",
              "tell changes -ell into -old: told, twice.",
              "tell and sell are the same family: told and sold."),
"think":     ("think","thought","thought",
              "think goes to -ought: thought, twice.",
              "thought, bought and brought all rhyme."),
"throw":     ("throw","threw","thrown",
              "throw belongs to the -ew / -own family: threw for the past simple and thrown for the participle.",
              "threw and through sound the same but they are different words."),
"understand":("understand","understood","understood",
              "understand follows stand: understood, twice.",
              "If you know stand - stood, you already know this one."),
"wake":      ("wake","woke","woken",
              "wake changes a into o for the past simple and the participle adds -n: woken.",
              "woke is the past simple; woken follows have or has."),
"wear":      ("wear","wore","worn",
              "wear changes ea into o: wore for the past simple and worn for the participle.",
              "wear and tear work the same way: wore/worn and tore/torn."),
"win":       ("win","won","won",
              "win changes i into o: won, twice.",
              "won sounds exactly like the number one."),
"write":     ("write","wrote","written",
              "write changes i into o for the past simple and the participle doubles the t: written.",
              "Two t in written. wrote is the past simple."),
}

# variantes extra que el corrector tambien acepta, por columna
EXTRA = {
  "be":    {1: ["was","were","was were","were was"]},
  "get":   {2: ["gotten"]},          # gotten es la forma americana
  "light": {1: ["lighted"], 2: ["lighted"]},
  # La hoja pone LAY en la columna de infinitivo en el mini test 4 version 2,
  # pero la lista de la clase usa lie - lay - lain. Se aceptan las dos lecturas.
  "lay":   {1: ["lay"], 2: ["lain"]},
}
